theme: jekyll-theme-hacker
title: Welcome to Rosh PR source hub
description: An end-to-end product developer. Having wide variety of experience in multiple technologies. Working on architecting & deploying Juniper products on AWS.
