# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Rosh PR
tagline:          'DevOps Source hub'
description:      'An end-to-end product developer and cloud Architect specializing in deploying enterprise grade products on Public clouds. Sole architect of deploying <a href="https://www.juniper.net/us/en/solutions/sd-wan-sd-lan/" target="_blank">CSO SDWan</a> solution on AWS.'
url:              https://roshpr.github.com
baseurl:          '/roshpr.github.com'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
remote_theme: fongandrew/hydeout
author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
